# Generated by Django 4.0.6 on 2022-11-02 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.FloatField()),
                ('ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ID', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(0, '사기'), (1, '욕설'), (2, '거래파기'), (3, '기타')], default=0)),
                ('ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(0, '광고'), (1, '사기'), (2, '욕설'), (3, '기타')], default=0)),
                ('buyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='buy.buy')),
            ],
        ),
    ]
