# Generated by Django 4.0.6 on 2022-11-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_reportuser_reportpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='category',
            field=models.IntegerField(choices=[(0, '광고'), (1, '사기'), (2, '욕설'), (3, '기타')], default=0),
        ),
        migrations.AddField(
            model_name='reportuser',
            name='category',
            field=models.IntegerField(choices=[(0, '사기'), (1, '욕설'), (2, '거래파기'), (3, '기타')], default=0),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
