# Generated by Django 4.0.6 on 2022-08-04 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('category', models.IntegerField(choices=[(0, '식재료'), (1, '생필품'), (2, 'OTT'), (3, '배달')], default=0)),
                ('wpeople', models.IntegerField()),
                ('people', models.IntegerField(default=1, null=True)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pur_photo')),
                ('good', models.IntegerField(default=0, null=True)),
                ('ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
