# Generated by Django 4.0.6 on 2022-11-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
