# Generated by Django 4.0.6 on 2022-09-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='check_chat',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
