# Generated by Django 4.0.6 on 2022-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='buy',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
