# Generated by Django 4.0.6 on 2022-08-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_remove_buy_good_alter_buy_photo_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
    ]
