# Generated by Django 4.0.6 on 2022-08-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_alter_buy_lat_alter_buy_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='long',
        ),
    ]
