# Generated by Django 4.0.6 on 2022-09-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_buy_check_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='check_chat',
            field=models.BooleanField(default=0),
        ),
    ]
