# Generated by Django 4.0.6 on 2022-08-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_buy_like_count_delete_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='join_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
