# Generated by Django 4.0.6 on 2022-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_buy_join_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='join_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
