# Generated by Django 4.0.6 on 2022-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_alter_buy_check_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='check_chat',
            field=models.BooleanField(default=False),
        ),
    ]
