# Generated by Django 4.0.6 on 2022-11-09 12:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='post_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
