# Generated by Django 4.0.6 on 2022-11-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('buy', '0001_initial'),
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_posts',
            field=models.ManyToManyField(blank=True, related_name='join_users', to='buy.buy'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_frees',
            field=models.ManyToManyField(blank=True, related_name='freeLike_users', to='free.free'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='buy.buy'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
