# Generated by Django 4.0.6 on 2022-08-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_buy_like_count_delete_bookmarks'),
        ('accounts', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='buy.buy'),
        ),
    ]
