# Generated by Django 4.0.6 on 2022-08-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_buy_join_count'),
        ('accounts', '0003_user_like_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_posts',
            field=models.ManyToManyField(blank=True, related_name='join_users', to='buy.buy'),
        ),
    ]
