# Generated by Django 4.0.6 on 2022-09-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
