# Generated by Django 4.0.6 on 2022-11-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms',
            field=models.BooleanField(default=False),
        ),
    ]
