# Generated by Django 4.0.6 on 2022-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0002_free_like_count'),
        ('accounts', '0004_user_join_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_frees',
            field=models.ManyToManyField(blank=True, related_name='freeLike_users', to='free.free'),
        ),
    ]
