# Generated by Django 4.0.6 on 2022-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
